name: Generate Snake Animation

on:
  schedule:
    - cron: "0 20 * * *"  # Runs at 20:00 UTC daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
